### ISSUE TITLE
Виджет сообщений сообщества ВК привлекает слишком много внимания

### ISSUE THREAD

**Issue by citxx** [andgein/SIStema#242]
Он постоянно отвлекает от основных действий.

Хочется:
- [ ] Отключить анимацию
- [ ] Показывать всплывающую подсказку только до первого использования виджета

**Comment by citxx** [comment]
Говорят, что можно задавать «интервал раскрытия и вот это все»: https://vk.com/dev/CommunityMessages

Если сами не разберёмся, то есть у кого спросить.

**Comment by andgein** [comment]
В общем, отключили анимацию, а текст вообще не показываем пока.
