### ISSUE TITLE
Отдельная настройка для раздела задачи на странице экзамена

### ISSUE THREAD

**Issue by citxx** [andgein/SIStema#243]
Раздел, совпадающий с типом задачи не всегда бывает наиболее подходящим. Например, сейчас задача для параллели P очень странно смотрится в разделе с теоретическими задачами.

Также нет возможности изменить порядок разделов из админки.

Ещё с этой настройкой можно было бы делать отдельный раздел для задач группы A-ML.

**Comment by andgein** [comment]
Сделали тут всё, что хотели?

**Comment by citxx** [comment]
Да
