### ISSUE TITLE
Невидимый шаг для подтвердивших участие

### ISSUE THREAD

**Issue by citxx** [andgein/SIStema#290]
Хочется узнавать, подтвердил ли школьник участие в ЛКШ, без того, чтобы хардкодить название анкеты зачисленного. Для этого надо сделать невидимый шаг после анкеты зачисленного, который устанавливает соответствующий статус в базе.

Заодно надо навести порядок в статусах зачисления и отказов.

**Comment by andgein** [comment]
Подтверждение участия теперь — отдельный шаг, показываем его на странице со всеми шагами.
