### ISSUE TITLE
В джанго-админке теперь экранируется весь HTML

### ISSUE THREAD

**Issue by citxx** [andgein/SIStema#412]
Пример:
![selection_139](https://user-images.githubusercontent.com/743738/37560167-ea1e6978-2a33-11e8-8025-33bfb7c135c5.png)

**Comment by andgein** [comment]
Там же специальный атрибут allow_tags = True для этого навешивался? Или это при обновлении джанго сломалось?

**Comment by citxx** [comment]
Я подозреваю, что при обновлении на 2.0

**Comment by citxx** [comment]
https://stackoverflow.com/questions/47953705/how-do-i-use-allow-tags-in-django-2-0-admin

**Comment by andgein** [comment]
@citxx Ага, понятно
